(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const cfg=window.BUSINESS_CONFIG||{};
  const messages=cfg.messages||{};
  const wa=(msg=messages.general)=>`https://wa.me/${cfg.whatsapp}?text=${encodeURIComponent(msg||messages.general)}`;
  const productMsg=name=>`Hello Natraj Electronics, I am interested in ${name}. Please share price and availability.`;
  window.NE={cfg,wa,productMsg};
  function hydrate(){
    $$('[data-config]').forEach(el=>{const path=el.dataset.config.split('.'); let v=cfg; path.forEach(k=>v=v?.[k]); el.textContent=v||'';});
    $$('[data-link]').forEach(a=>{const type=a.dataset.link; const key=a.dataset.messageKey; const msg=a.dataset.message || (key&&messages[key]) || messages.general; if(type==='maps')a.href=cfg.googleMapsUrl; if(type==='call')a.href=cfg.phoneHref; if(type==='email')a.href=cfg.emailHref; if(type==='instagram')a.href=cfg.instagram; if(type==='owner')a.href=cfg.owner.profileUrl; if(type==='whatsapp')a.href=wa(msg);});
    $$('[data-owner-image]').forEach(img=>{img.src=cfg.owner.image; img.onerror=()=>{img.onerror=null; img.src=cfg.owner.fallbackImage};});
    $$('.year').forEach(el=>el.textContent=new Date().getFullYear());
  }
  function nav(){const b=$('.menu-toggle'),n=$('.nav-links'); if(b&&n)b.addEventListener('click',()=>{const o=n.classList.toggle('open');b.setAttribute('aria-expanded',o);b.textContent=o?'Close':'Menu'}); const p=location.pathname.split('/').pop()||'index.html'; $$('nav a').forEach(a=>{if((a.getAttribute('href')||'')===p)a.classList.add('active')});}
  function renderProducts(limitFeatured=false){const grid=$('#productGrid'); if(!grid||!window.PRODUCTS)return; const search=$('#productSearch'), filters=$('#productFilters'); let active='All'; const cats=['All',...new Set(PRODUCTS.map(p=>p.category))]; if(filters)filters.innerHTML=cats.map(c=>`<button class="filter-btn${c==='All'?' active':''}" type="button" data-cat="${c}">${c}</button>`).join(''); const draw=()=>{const q=(search?.value||'').toLowerCase(); const data=PRODUCTS.filter(p=>(!limitFeatured||p.featured)&&(active==='All'||p.category===active)&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)); grid.classList.toggle('best-seller-layout',limitFeatured); grid.innerHTML=data.map((p,i)=>`<article class="card product-card reveal ${limitFeatured&&i===0?'feature-tile':''}"><div class="product-media"><img src="${p.image}" alt="${p.name}" loading="lazy" width="640" height="400">${p.featured?'<span class="feature-badge">Featured</span>':''}</div><p><span class="badge">${p.category}</span></p><h3>${p.name}</h3><p class="muted">${p.description}</p><p class="price"><strong>${p.price}</strong></p><div class="action-row"><a class="btn btn-primary" href="${wa(productMsg(p.name))}" target="_blank" rel="noopener">Enquire on WhatsApp</a></div></article>`).join('')||'<p class="muted">No matching products. Edit js/products.js to add more items.</p>'; reveal();}; filters?.addEventListener('click',e=>{if(e.target.matches('.filter-btn')){active=e.target.dataset.cat; $$('.filter-btn',filters).forEach(x=>x.classList.remove('active')); e.target.classList.add('active'); draw();}}); search?.addEventListener('input',draw); draw();}
  function renderServices(){ $$('[data-services]').forEach(grid=>{grid.innerHTML=(window.SERVICES||[]).map(s=>`<article class="service-card reveal"><div class="service-icon">${s.icon}</div><h3>${s.title}</h3><p>${s.description}</p><a class="text-link" href="${wa(messages[s.messageKey]||messages.general)}" target="_blank" rel="noopener">${s.cta} →</a></article>`).join('')}); const t=$('#trustGrid'); if(t)t.innerHTML=(window.TRUST_ITEMS||[]).map(x=>`<article class="card reveal"><h3>${x}</h3><p class="muted">${trustText(x)}</p></article>`).join(''); const b=$('#b2bItems'); if(b)b.innerHTML=(window.B2B_ITEMS||[]).map(x=>`<span class="chip">${x}</span>`).join(''); const ac=$('#accessoryItems'); if(ac)ac.innerHTML=(window.ACCESSORY_CATEGORIES||[]).map(x=>`<span class="category-card">${x}</span>`).join('');}
  function trustText(x){return {"Personal Assistance":"Get help selecting suitable products.","Repair Support":"Talk to us when something stops working.","Wide Range":"Electronics, accessories and related products.","Business Support":"B2B and bulk requirements.","EMI Options":"Ask about available EMI options.","Local Convenience":"Visit the store and talk directly with the team."}[x]||''}
  function forms(){ $$('[data-enquiry-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(form)); const msg=`Hello Natraj Electronics,\n\nI have a B2B requirement.\n\nName: ${d.name||''}\nCompany: ${d.company||''}\nPhone: ${d.phone||''}\nEmail: ${d.email||''}\nRequirement: ${d.requirement||''}\nQuantity: ${d.quantity||''}\nMessage: ${d.message||''}`; location.href=wa(msg);}));}
  function reveal(){const els=$$('.reveal:not(.visible)'); if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible')); return;} const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible'); io.unobserve(e.target);}}),{threshold:.12}); els.forEach(e=>io.observe(e));}
  document.addEventListener('DOMContentLoaded',()=>{hydrate(); nav(); renderProducts(document.body.dataset.page==='home'); renderServices(); forms(); reveal();});
})();
