const PRODUCTS = [
  { name: "Featured Television Placeholder", category: "TV", image: "assets/images/products/product-tv.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for televisions or display products available at the store.", featured: true },
  { name: "Home Appliance Placeholder", category: "Appliances", image: "assets/images/products/product-appliance.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for refrigerators, washing machines, air conditioners, or other appliances.", featured: true },
  { name: "Mobile Device Placeholder", category: "Mobile", image: "assets/images/products/product-mobile.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for smartphones, mobile accessories, and related products.", featured: true },
  { name: "Computer & Laptop Placeholder", category: "Computer", image: "assets/images/products/product-laptop.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for laptops, computers, peripherals, and office tech.", featured: false },
  { name: "Audio System Placeholder", category: "Audio", image: "assets/images/products/product-audio.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for speakers, sound systems, headphones, and audio accessories.", featured: false },
  { name: "CCTV & Security Placeholder", category: "CCTV", image: "assets/images/products/product-cctv.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for CCTV, surveillance, security, and installation enquiries.", featured: false },
  { name: "Accessories Placeholder", category: "Accessories", image: "assets/images/products/product-accessory.svg", price: "Contact for Price", availability: "Availability to be confirmed", description: "Editable placeholder for cables, chargers, remotes, adapters, and useful add-ons.", featured: false }
];
