const PRODUCTS = [
  { name: "Electronics Purchase", category: "Electronics", image: "assets/images/products/product-tv.svg", price: "Contact for Price", description: "Electronics and related products for everyday home, shop and business requirements.", featured: true },
  { name: "Mobile & Accessories", category: "Mobile & Accessories", image: "assets/images/products/product-mobile.svg", price: "Contact for Price", description: "Mobile accessories and device essentials. Ask the store team for current availability.", featured: true },
  { name: "Mobile Repair Enquiry", category: "Mobile Repair", image: "assets/images/products/product-mobile.svg", price: "Ask for Estimate", description: "Fast, reliable mobile repair assistance after checking the device and issue.", featured: true },
  { name: "Electronics Repair Support", category: "Electronics Repair", image: "assets/images/products/product-appliance.svg", price: "Ask for Estimate", description: "Troubleshooting and repair support for relevant electronics and accessory issues.", featured: false },
  { name: "Wiring & Electrical Items", category: "Wiring & Electrical Items", image: "assets/images/products/product-cctv.svg", price: "Contact for Price", description: "Wiring and electrical items for everyday requirements. Confirm exact item availability by WhatsApp.", featured: false },
  { name: "Fans & Coolers", category: "Fans & Coolers", image: "assets/images/products/product-appliance.svg", price: "Contact for Price", description: "Fans, coolers and related accessories. Ask about current options before visiting.", featured: true },
  { name: "DJ Sets & Equipment", category: "DJ Sets & Equipment", image: "assets/images/products/product-audio.svg", price: "Contact for Price", description: "DJ sets, audio equipment, cables and related DJ accessories for sound requirements.", featured: true },
  { name: "Home Electronics", category: "Home Electronics", image: "assets/images/products/product-tv.svg", price: "Contact for Price", description: "Home electronics category for purchase enquiries and suitable product guidance.", featured: false },
  { name: "Accessories", category: "Accessories", image: "assets/images/products/product-accessory.svg", price: "Contact for Price", description: "Chargers, cables, earphones, cases, screen protectors, adapters and other accessories.", featured: false },
  { name: "B2B Solutions", category: "B2B Solutions", image: "assets/images/products/product-laptop.svg", price: "Request Quote", description: "Bulk and business electronics requirements for commercial customers and institutions.", featured: false },
  { name: "Easy EMI Options", category: "EMI Options", image: "assets/images/products/product-accessory.svg", price: "Ask About EMI", description: "Ask our team about available EMI options for eligible purchases.", featured: false }
];
const ACCESSORY_CATEGORIES = ["Chargers", "Cables", "Earphones", "Headphones", "Mobile Cases", "Screen Protectors", "Adapters", "Other Accessories"];
